---
name: Build ffmpeg dlls

# yamllint disable rule:line-length
# yamllint disable-line rule:truthy
on:
  # push:
    # tags:
      # - 'v*.*.*'
  workflow_dispatch:

defaults:
  run:
    shell: cmd

jobs:
  MSVC:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md
        os: [windows-2022]
        triplet: [x64-windows, x86-windows]
        include:
          - os: windows-2022
            triplet: x64-windows
            # https://github.com/microsoft/vcpkg/commit/760bfd0c8d7c89ec640aec4df89418b7c2745605
            vcpkgCommitId: '760bfd0c8d7c89ec640aec4df89418b7c2745605'
            vcpkgPackages: 'ffmpeg'
            configuration: 'x64'
            pluginDir: 'x64'
          - os: windows-2022
            triplet: x86-windows
            vcpkgCommitId: '760bfd0c8d7c89ec640aec4df89418b7c2745605'
            vcpkgPackages: 'ffmpeg'
            configuration: 'x86'
            pluginDir: 'win32'
    env:
      buildDir: '${{ github.workspace }}/build/'
      ffmpegVer: '7.1.1'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Restore from cache the previously built ports. If cache-miss, download and build vcpkg (aka "bootstrap vcpkg").
      # - name: Restore from cache and install vcpkg
      - name: Install vcpkg and build packages
        # Download and build vcpkg.
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: false
          # Caching is not working anymore in run-vcpkg@v7 as before
          # This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset
          doNotCache: true
          # Location of vcpkg in the Git repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId}}'
          vcpkgTriplet: ${{ matrix.triplet }}
          vcpkgArguments: '${{ matrix.vcpkgPackages }}'
          # Ensure the vcpkg artifacts are cached, they are generated in the 'CMAKE_BINARY_DIR/vcpkg_installed' directory.
          # additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed
      - name: Collect files
        run: |
          # ffmpeg dlls: avcodec, avdevice, avfilter, avformat, avutil
          xcopy /Y /D vcpkg\installed\${{ matrix.triplet }}\bin\av*.dll deploy\plugins\${{ matrix.pluginDir }}\
          # ffmpeg dlls: swresample, swscale
          xcopy /Y /D vcpkg\installed\${{ matrix.triplet }}\bin\sw*.dll deploy\plugins\${{ matrix.pluginDir }}\
      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg_${{ env.ffmpegVer }}_dlls_${{ matrix.pluginDir }}
          path: deploy/
